### ISSUE TITLE
MFC is broken

### ISSUE THREAD

**Issue by jrudess** [jrudess/mfc_cb.node#11]
MFC recently changed something.  mfc_cb.node uses the MFCAuto library, so once MFCAuto is updated, mfc_cb.node will start working again.

**Comment by pusspounder** [comment]
Confirming MyFreeCams capture is broken as of right now.

:(

**Comment by jrudess** [comment]
Initial workaround has been pushed to the development branch;  Seems to be working but needs more people to test.

**Comment by TMily** [comment]
lol testing~~~

**Comment by jrudess** [comment]
Fixed in 0.3.0
