### ISSUE TITLE
Allow placing recordings in model name directories

### ISSUE THREAD

**Issue by jrudess** [jrudess/mfc_cb.node#12]
Rather than dumping all final recordings in one directory, this enhancement is to add a flag to enable creating sub-directories with the models name, and placing the model recordings there instead.

**Comment by SearchAndDestroy** [comment]
Good idea.
Also to add to that idea,  would it be easy to freeze the model name? i.e. always save model 12345678 as MyAwesomeModel and not follow her name change?

**Comment by jrudess** [comment]
Associating a fixed name for a given model ID would be a nice feature, but doesn't implement easily due to multi-site support for CB in the current code micro-architecture.   Will consider this as a future enhancement though.

Released in 0.3.2
