### ISSUE TITLE
Optimize Models Checking (Chaturbate)

### ISSUE THREAD

**Issue by fanout96** [jrudess/mfc_cb.node#19]
parsing site for search for models is not the best way, I suggest taking the data from here: 
`http://chaturbate.com/affiliates/api/onlinerooms/?wm=mnzQo&format=json&gender=f`

**Comment by jrudess** [comment]
Thanks for the info!  I agree this is a better method.

**Comment by fanout96** [comment]
There is another idea, with the help of these data, you can track the blocking of countries, the models of Chaturbate. That allows you to bypass locks, for example, using: https://recgasm.com/

**Comment by jrudess** [comment]
There are some minor issues with this approach.   If a model disconnects, the fetched JSON will still report that the model has current_show = 'public'.  I've seen the model stay in the 'onlinerooms' JSON for up to 25 minutes after she has logged out.

The script now uses current_show from the returned JSON to detect models that are actively streaming, and then fetching the m3u8 stream will fail.  The temporary solution is to suppress errors that used to fire when fetching the m3u8 failed.

The CB code now matches the MFC code and prints model status updates (model is in private, model is in public chat, model is away, etc).  So the downside is that when starting up the script, it will falsely report that a model is in public chat when she is not even online.  This is likely to confuse the end-user and make them think the script is broken and not capturing models correctly.

When a model is offline, fetching https://chaturbate.com/modelname/ redirects to the login page.  So the better longterm solution is to do an early fetch of this page, and if the login page is returned, treat the model as offline to supress the printouts as well.

**Comment by jrudess** [comment]
Released in v0.4.
