### ISSUE TITLE
CB model online

### ISSUE THREAD

**Issue by saren89** [jrudess/mfc_cb.node#2]
the part for CB no long works, it shows than no model is online when in fact they are,

**Comment by SearchAndDestroy** [comment]
I have the same issue but if I change the line 38 from cb.js to
`return session.get('https://chaturbate.com/?page=' + page);`
it correctly shows the number of models online and starts recording correctly :)

**Comment by jrudess** [comment]
Thanks for the report!  I can't remember why I was using the followed_page section other than the original capturbate.node may have been.   Will test this patch out and push a new release.

**Comment by jrudess** [comment]
Fixed in [v0.2.3.](https://github.com/jrudess/mfc_cb.node/releases/tag/0.2.3)
