### ISSUE TITLE
At connection to MFC, process node.js dies

### ISSUE THREAD

**Issue by fanout96** [jrudess/mfc_cb.node#22]
At me a problem, at connection to MFC, process node.js dies and recordings not be converting to mp4.

logs: 
![bug](https://user-images.githubusercontent.com/28878036/27589678-e982ef6a-5b54-11e7-95e5-5351abecc663.PNG)

last log - with normal loading:
![default](https://user-images.githubusercontent.com/28878036/27589780-517bef86-5b55-11e7-9bbe-cfb5c41c9b63.PNG)

**Comment by fanout96** [comment]
i'm using latest development branch

**Comment by jrudess** [comment]
Can you try running for a bit without using 'forever'?   I believe the network connectivity problems are fixed with the latest code in both master and development branches, and I'm curious if the 'forever' script is having some impact here.
