### ISSUE TITLE
ask a question 

### ISSUE THREAD

**Issue by p1020119** [jrudess/mfc_cb.node#31]
how many models names can i put in config.yml one time? i fond if i have lots of  models, not easy to put in  config.yml.  must i do like this format ?- (+) names? mfcmodels:
                                                         - 11111111
                                                         - 22222222
                                                        -  3333333
                                                         cbmodels:
                                                          - aaaaaa
                                                         - bbbbbb

**Comment by ms6676749** [comment]
As many as your connection can handle.  Yes, you have to put them in that format, yaml is very strict when it comes to formatting.

You should add them (model names) to updates.yml (see below) that will add them to your config.yml in the proper format:

	includeMfcModels: [model1,model2,model3,model4,etc]
	excludeMfcModels: []
	includeCbModels: [cbmodel1,cbmodel2]
	excludeCbModels: []
