### ISSUE TITLE
Testing help requested

### ISSUE THREAD

**Issue by jrudess** [jrudess/mfc_cb.node#34]
Not sure how many people will see this, but I've done a pretty large overhaul on the code-base.  If you're able, please download the development branch and give it a whirl and send any issues you find my way.

**Comment by YDdraigGoch** [comment]
Hello again.
It works in that it records but then when a model goes offline a message says _x_ is not actually online, CB is not updating properly. Also periodically an error is thrown "CB did not respond after 20 seconds"

**Comment by ggezz** [comment]
Downloaded the dev branch and have tested it out it records all cb models fine but console seems to say "X is not actually online, CB is not updating properly." but it still records them fine. As for mfc some models don't record at all not sure why this is.

**Comment by SearchAndDestroy** [comment]
I am also getting the "is not actually online, CB is not updating properly." message and this error after a few hours running.
Node is version 8.6.0
`<--- Last few GCs --->

[21084:000001DD3B43DD80] 17274502 ms: Mark-sweep 1404.7 (1457.1) -> 1404.7 (1434.6) MB, 154.8 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 155 ms) last resort
[21084:000001DD3B43DD80] 17274664 ms: Mark-sweep 1404.7 (1434.6) -> 1404.7 (1434.1) MB, 162.1 / 0.0 ms  last resort


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000001EF6AEA8799 <JSObject>
    2: _make [D:\XXX\mfc_cb.node_DEV\node_modules\cheerio\lib\cheerio.js:126] [bytecode=000000C933DC17A9 offset=2](this=0000011F13D7FD91 <initialize map = 000001F283608559>,dom=00000089EB0418B9 <JSArray[12956]>,context=000001C175582311 <undefined>)
    3: arguments adaptor frame: 1->2
    5: find [D:\XXX\mfc_cb.node_DEV\node_modules\cheerio\lib\api\traversing.js:40] [bytecode=00000090F28732F...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

**Comment by YDdraigGoch** [comment]
Latest development update [#f4dd295](https://github.com/jrudess/mfc_cb.node/commit/f4dd295d6780e53b2803d1d71b57c85dd2ecb49d) - throws `MFC* [ERROR] TypeError: colors[theme[style]] is not a function`
*and CB too

**Comment by jrudess** [comment]
I believe that the error messages about CB are both CB server problems.  

The CB servers don't update ther 'online model state' very fast, with sometimes up to 10 minutes of delay.   So the script queries CB to see if model is on and see's the model is on, but when it tries to fetch their video stream the video stream doesn't exist, and this error prints out.   The problem is that the CB servers are just serving stale 'online' data, and when this happens you can even see the models avatar on the CB frontpage even though they aren't online anymore.

The "CB did not respond after 20 second error" is also a CB problem.  Script sends them an https request, and gets no response back.  

The error about theme/style is most likely due to having a stale config.yml.  There are new colors that are defined in the latest version and you'll need to copy those into your config.yml.    I'll fix up the yml parser to add default colors when entries are missing from config.yml to prevent this in the future.

@SearchAndDestroy I saw that once, thanks for reporting it.   It's very possible that the blessed UI library I'm using has a memory leak, and I'm seeing if I can track anything down

Thanks for all the reports!

**Comment by jrudess** [comment]
CB should be much faster and have less errors now.

**Comment by YDdraigGoch** [comment]
Hello again.
Just to let you know since your last commit, it is no longer recording. Also it used to show a list of models I put in config and what the script was recording but now it's just a blue line at the bottom of the terminal.

**Comment by jrudess** [comment]
@YDdraigGoch on every update you need to start with the newer version of config.yml and copy over your model lists.   This behavior is because you are missing some new entries in config.yml.
