### ISSUE TITLE
New better way getting model stream url

### ISSUE THREAD

**Issue by fanout96** [jrudess/mfc_cb.node#35]
`https://chaturbate.com/api/chatvideocontext/modelname` - new data source with json format

**Comment by jrudess** [comment]
I've updated the development branch to use this new method.

**Comment by fanout96** [comment]
If the broadcaster has a country lock, the data is returned:
{"status": 401, "code": "access-denied", "detail": "This room is not available to your region or gender."}
It is necessary to make this state. =)

**Comment by fanout96** [comment]
Also I noticed that the new method also does not take into account some users, it would be possible to make both variants of getting the list and selecting the mode in the config file

**Comment by jrudess** [comment]
I commited a patch for dealing with access-denied data.   I don't happen to know any models in that would return that data for me so let me know if there are issues with it.

I need to think more about supporting both methods.  There are some minor, but annoying structural differences between the prior and new method in the code.   I might copy the pre-change cb module to cblegacy and let it have it's own separate model list entries in config.yml, then both can be supported at once.

**Comment by fanout96** [comment]
In the list the state does not change, in the console writes "Unknown model check the spelling.". Would be better to do so that if the site returns a 401 code, then getting status from detail. Has so far found only 2 cases of returning such an data:

`{"status": 401, "code": "access-denied", "detail": "Room is deleted."}`
`{"status": 401, "code": "access-denied", "detail": "This room is not available to your region or gender."}`

**Comment by jrudess** [comment]
Thanks for the url.   Committed a fix for 401 case.

**Comment by jrudess** [comment]
@fanout96 do you have a rough guess, as a percentage, how many models don't work with the new method?   Also what happens in this case?  Is no JSON data returned from the new url, or some kind of error JSON?

**Comment by jrudess** [comment]
Released in v0.6.0
