### ISSUE TITLE
CB scoffs

### ISSUE THREAD

**Issue by fanout96** [jrudess/mfc_cb.node#37]
At work CB sometimes ceases to be processed, while active records continue to be recorded, but new ones do not appear. And adding / removing models does not work. I think at some point "Promise" just dies. 
![2](https://user-images.githubusercontent.com/28878036/33804624-d7272a6a-ddb9-11e7-9c86-fa2518a460c5.PNG)
P.S. Perhaps this happens when the connection to the Internet is reconnecting

**Comment by jrudess** [comment]
Looks like I lost a timeOut during the changeover to new CB method.   I think the following patch may address this.

diff --git a/cb.js b/cb.js
index d4c63f8..73efdeb 100644
--- a/cb.js
+++ b/cb.js
@@ -86,7 +86,7 @@ class Cb extends site.Site {
         let isBroadcasting = 0;
 
         return Promise.try(function() {
-            return fetch(url);
+            return fetch(url, {timeout: me.timeOut});
         }).then((res) => res.json()).then(function(json) {
             const listitem = me.streamerList.get(nm);

**Comment by fanout96** [comment]
It looks like it all happens when reconnecting.
Now I will replace the line and see how it will be =)

**Comment by fanout96** [comment]
UPD: It works fine, can be committed
