### ISSUE TITLE
.jshintrc error

### ISSUE THREAD

**Issue by forsomefun** [jrudess/mfc_cb.node#6]
There seems to be an error we this files gets corrupted and stops working correctly 

The program responds by spitting out this message

 UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected end of input
(node:15076) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Strangely CB models continue to be recorded but MFC models are not
One can Create this error by deleting the .jshintrc file and running the program

Fixing it requires replacing the file

**Comment by jrudess** [comment]
I did not think the .jshintrc file was used by node-js.  I would think that file is only used by the jshint linter.  However, I may very well be wrong.   I recently added the following line to the file.  You might try deleting just this line and see if the problem stops occurring.  I have not been able to replicate this yet.

`"undef"      : true,`

**Comment by forsomefun** [comment]
I deleted the line
I will have to wait to see if it was stable.
