### ISSUE TITLE
autodelete after conversion

### ISSUE THREAD

**Issue by SearchAndDestroy** [jrudess/mfc_cb.node#8]
I have set:
autoConvertType: mp4
autoDelete: false
because I have sync problems with the .ts files from CB but the original .ts file is deleted. Is it not supposed to be not deleted according to autoDelete being set to false?
Also, is there a way to preserve the file timestamps from the .ts file to the converted file i.e. the timestamps from the start of the recording?

**Comment by jrudess** [comment]
The autoDelete flag is a development flag that causes all recorded files to be deleted.  It doesn't prevent the .ts file from being removed after conversion is finished.

When autoConvertType is set to mp4 or mkv, the .ts file is always deleted.  The only way to keep the .ts currently is to disable mp4/mkv conversion with:
autoConvertType: ts

ffmpeg is the program that is responsible for doing the conversions, so this script does not control the timestamp of the converted file.   You can have the year, day, month, hour, and second in the filename itself, however, which lets you know the exact time that the recording started.

dateFormat: YYYYMMDD-HHmmss

**Comment by SearchAndDestroy** [comment]
ok thanks :)
I will set autoConvertType: none and have a script to convert the CB files manually for now

**Comment by jrudess** [comment]
I'll push a change to the development branch later today which will add the following new flag to keep the ts file and still perform the conversions:

keepTsFile: yes

**Comment by SearchAndDestroy** [comment]
Thank you :)
I am using another script for CB that doesn't use ffmpeg to capture and I have no sync problems but I would  prefer to use just this script to handle both sites.

**Comment by jrudess** [comment]
If the other script is available publicly, can you point me to it?  I noticed some choppy CB captures a month or two ago, but I haven't been using CB at all recently so haven't dug into it more deeply.

**Comment by SearchAndDestroy** [comment]
It's here http://stream-recorder.com/forum/showpost.php?p=88372&postcount=148

**Comment by SearchAndDestroy** [comment]
Did you get the link for the CB recording script ?
I posted it in the issue thread?
If not it's here:
http://stream-recorder.com/forum/showpost.php?p=88372&postcount=148
In the mean time, I switched CB recording off.

**Comment by jrudess** [comment]
Got some info from some other folks to ignore the edge part of the URL.  For example, edge13 server is pretty bad and causes lots of disconnects, while edge35 is good.  This may depend on where you are located.   

Plan right now is to add a new config.yml option.  When set, it will specify a list of edge* servers to choose from.  When not set, it will just use the server provided by CB.

**Comment by jrudess** [comment]
Feature has been pushed into development branch.  Will merge to master for next release.

`keepTsFile: true`

**Comment by jrudess** [comment]
Released in 0.3.0
