### ISSUE TITLE
file size limit

### ISSUE THREAD

**Issue by TMily** [jrudess/mfc_cb.node#9]
i use this script on a VPS and set captureDirectory in VPS‘s Local SSD , completeDirectory in remote netdisk. so any way to auto cut ts file? because VPS’s SSD space is limited.

**Comment by jrudess** [comment]
This has been on my mental list of things to do for a while.  It should be possible.

**Comment by TMily** [comment]
thx~~

**Comment by jrudess** [comment]
A first pass implementation is committed to the development branch.  Please try this out and let me know how it works for you, or if you run into issues.

- config.yml entry is maxSizeBytes
- maxSizeBytes = 0 means no size limit
- The file size is checked at intervals specified by modelScanInterval
- If the interval is longer (default=300s) the final file size will often be larger than maxSizeBytes
- The size being checked is the .ts capture size.  The final converted .mp4 or .mkv can be noticeably smaller than maxSizeBytes, especially for 320x200 low frame rate captures.

**Comment by TMily** [comment]
thx~~ testing

**Comment by TMily** [comment]
![20170417124654](https://cloud.githubusercontent.com/assets/3784599/25079101/ffbefd76-236b-11e7-93ec-a9a61656ee64.png)
BUG?

**Comment by jrudess** [comment]
Yeah, it's a problem, working on a solution.

**Comment by jrudess** [comment]
Pushed a fix.  Was a sync vs async problem with the new code.

**Comment by TMily** [comment]
thx~~i up to date script  and testing~ but MFC is not work orz~~ if i don't stop old script MFC just work fine~~
P.S if i record MFC & CB when i want stop i need input Ctrl-C twice?

**Comment by jrudess** [comment]
Released in 0.3.0

**Comment by jrudess** [comment]
Have run into some race conditions where two caps of the same model can end up running concurrently.   I believe it is related to the maxSizeBytes logic.   Reopening issue for now.

**Comment by jrudess** [comment]
All issues should now be resolved with v0.3.1
